mybatis:
  # 错误:config-location: classpath:mapper/UserMapper.xml
  mapper-locations: classpath:mapper/*.xml

token:
  secret: hearing-secret
  expiration: 86400 # 单位: s---86400
  header: loginToken

spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aiface?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
#  security:
#    user:
#      name: hearing
#      password: 123456

